## 1
name: Generate a Sign APK

## Actions that will be executed when you push code currently none
on:
  push:

before_install:
  - chmod +x gradlew

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      # 1

      - name: Checkout code

        uses: actions/checkout@v2

      # 2 

      - name: Generate Release APK

        run: ./gradlew assembleRelease
        

      # 3

      - uses: actions/upload-artifact@master

        with:

          name: release.apk

          path: ${{steps.sign_app.outputs.signedReleaseFile}}

   
